export const ALL_REPORT_REQUEST = "ALL_REPORT_REQUEST"
export const ALL_REPORT_SUCCESS = "ALL_REPORT_SUCCESS"
export const ALL_REPORT_FAIL = "ALL_REPORT_FAIL"


export const NEW_REPORT_REQUEST = "NEW_REPORT_REQUEST"
export const NEW_REPORT_SUCCESS = "NEW_REPORT_SUCCESS"
export const NEW_REPORT_FAIL = "NEW_REPORT_FAIL"


export const REPORT_DETAILS_REQUEST = "REPORT_DETAILS_REQUEST"
export const REPORT_DETAILS_SUCCESS = "REPORT_DETAILS_SUCCESS"
export const REPORT_DETAILS_FAIL = "REPORT_DETAILS_FAIL"

export const ASSIGN_REPORT_REQUEST = "ASSIGN_REPORT_REQUEST"
export const ASSIGN_REPORT_SUCCESS = "ASSIGN_REPORT_SUCCESS"
export const ASSIGN_REPORT_FAIL = "ASSIGN_REPORT_FAIL"

export const EMPLOYEE_ASSIGNED_REPORT_REQUEST = "EMPLOYEE_ASSIGNED_REPORT_REQUEST"
export const EMPLOYEE_ASSIGNED_REPORT_SUCCESS = "EMPLOYEE_ASSIGNED_REPORT_SUCCESS"
export const EMPLOYEE_ASSIGNED_REPORT_FAIL = "EMPLOYEE_ASSIGNED_REPORT_FAIL"


export const UPDATE_REPORT_REQUEST = "UPDATE_REPORT_REQUEST"
export const UPDATE_REPORT_SUCCESS = "UPDATE_REPORT_SUCCESS"
export const UPDATE_REPORT_FAIL = "UPDATE_REPORT_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"
